@startuml
digraph HC2H {

  label=<
<B>Two-Handed Heavy Club Skill Progression - Part 2/2</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
Diagram by dznz based on Mark Wildman's teachings.<BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
Source: <B>https://github.com/dznz/wildman-skill-trees</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
More by Mark Wildman - <B>https://www.wildmanathletica.com</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
<I>
© 2023. This work is openly licensed with CC BY-NC-SA 4.0<BR ALIGN="RIGHT"/>
http://creativecommons.org/licenses/by-nc-sa/4.0/<BR ALIGN="RIGHT"/>
</I>
  >
  graph [labeljust=r]
  graph [fontname="Helvetica,Arial,sans-serif"]
  
  node [colorscheme="paired12"]
  node [fontname="Helvetica,Arial,sans-serif"]
  node [shape=record,style="rounded,filled"]
  edge [fontname="Helvetica,Arial,sans-serif"]
  node [color=2, fillcolor=1];

  subgraph "primary" {
    node [color=12, fillcolor=11]
    ' node [fontname="Helvetica Bold,Arial Bold,sans-serif",fontsize=16]
    node [margin=0.2]
    mov_cap;
    mov_40_swipe;
  }
  subgraph "secondary" {
    node [color=8, fillcolor=7]
    mov_kneelsc; mov_sblungepull; mov_fbpull; mov_kneelbackswing; mov_fbpullsit; mov_sblungepullbot; mov_fbpullsitpress; mov_altshinbox; mov_altshinboxfrpress; mov_sblungepullsbpress; mov_squatpress; mov_millprep
    mov_incirclesquat; mov_outcirclesquat; mov_39_pullsquat;
  }

  subgraph "prereq" {
    node [color=4, fillcolor=3]
    pre_shinbox [label="{{BW|Shin Box}}"]
    ext_2h_deadclean          [label="{{2H-04|Dead Clean}}"                                          URL="https://www.youtube.com/watch?v=69RGME9RTcY&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=4"]
    ext_2h_incircle       [label="{{2H-05|Inside Circle}}"                                       URL="https://www.youtube.com/watch?v=Mh6iWcLbE3k&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=5"];
    ext_2h_sc                 [label="{{2H-09|Shield Cast}}"                                         URL="https://www.youtube.com/watch?v=W-iHvrjn72k&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=9"];
    ext_2h_backposside2side  [label="{{2H-08|Back Position\nSide to Side Swing}|SWING BEHIND HEAD}" URL="https://www.youtube.com/watch?v=GKwGiB2UwyM&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=8"]
    ext_2h_frontpress         [label="{{2H-13|Front Press}}"                                         URL="https://www.youtube.com/watch?v=HBRWtm3tTp4&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=15"]
    ext_2h_outcircle      [label="{{2H-06|Outside Circle}}"                                      URL="https://www.youtube.com/watch?v=QzMzCal-MYM&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=6"];
    ext_2h_pullover           [label="{{2H-07|Pullover}|CLUB BEHIND HEAD}"                           URL="https://www.youtube.com/watch?v=jpIn1Sumg78&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=7"]
    ext_2h_squat              [label="{{2H-10|Balance Squat}}"                                       URL="https://www.youtube.com/watch?v=LSXticZ67Pw&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=11"]
    ext_2h_stepbacklunge      [label="{{2H-17|Balance Step\nBack Lunge}}"                            URL="https://www.youtube.com/watch?v=dNrYT5iU7BQ&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=26"]
    ext_2h_swingclean         [label="{{2H-11|Swing Clean}|DECELERATE WEIGHT}"                       URL="https://www.youtube.com/watch?v=0oRuCQOkPRo&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=12"]
  }

  subgraph "extra" {
    node [color=6, fillcolor=5]
    
  }

  subgraph "aux" {
    node [color=10, fillcolor=9];
    
  }

  // Heavy Club Sequence
  
  mov_kneelsc            [label="{{23|Half-Kneeling Shield Cast}}"                           URL="https://www.youtube.com/watch?v=yHIEZN0Nl_U&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=42"];
  mov_sblungepull        [label="{{24|Step-Back Lunge\nPullover at Top}}"                    URL="https://www.youtube.com/watch?v=yHIEZN0Nl_U&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=44"];
  mov_kneelbackswing     [label="{{25|Half-Kneeling\nBack Position Swing}}"                  URL="https://www.youtube.com/watch?v=XH_HFWZQt4c"]
  mov_fbpull             [label="{{26|Flat Back Pullover}}"                                  URL="https://www.youtube.com/watch?v=yHIEZN0Nl_U&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=45"];
  mov_fbpullsit          [label="{{27|Flat Back Pullover Situp}}"                            URL="https://www.youtube.com/watch?v=Ii2WZgl5mHA"]
  mov_sblungepullbot     [label="{{28|Step-Back Lunge\nPullover at Bottom}}"                 URL="https://www.youtube.com/watch?v=UpY9zHuTZds"]
  mov_fbpullsitpress     [label="{{29|Flat Back Pullover\nSitup Press}}"                     URL="https://www.youtube.com/watch?v=8VL8tvinc28"]
  // Missing 30, could be step-back front press
  mov_sbfrontpress       [label="{{30?|Step-Back Lunge\nFront Press}}"]
  mov_altshinbox         [label="{{31|Balance\nAlternating Shin Box}}"                       URL="https://www.youtube.com/watch?v=jogIwgDj0KM"]
  mov_incirclesquat      [label="{{32|Inside Circle Squat}}"                                 URL="https://www.youtube.com/watch?v=icFHo5ufhUc"]
  mov_altshinboxfrpress  [label="{{33|Alt Shinbox Front Press}}"                             URL="https://www.youtube.com/watch?v=D2AJzIVufeY&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=47"];
  mov_outcirclesquat     [label="{{34|Outside Circle Squat}}"                                URL="https://www.youtube.com/watch?v=z916C16iK54&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=49"]
  mov_sblungepullsbpress [label="{{35|Step-Back Lunge Pullover\nStep-Back Press}}"           URL="https://www.youtube.com/watch?v=1cXPBXfKNhU"]
  mov_squatpress         [label="{{36|Squat Press}}"                                         URL="https://www.youtube.com/watch?v=6p1niExqXSA"]
  mov_cap                [label="{{37|Clean & Press}}"                                       URL="https://www.youtube.com/watch?v=6kpEYglMJ1c"]
  mov_millprep           [label="{{38|Mill Prep}}"                                           URL="https://www.youtube.com/watch?v=G_OXuFs2bRs"]
  mov_39_pullsquat       [label="{{39|Pullover Squat}}"                                      URL="https://www.youtube.com/watch?v=3yf3VO2sd-4"];
  mov_40_swipe           [label="{{40|Technical Swipe}}"                                     URL="https://www.youtube.com/watch?v=nQ7npb0krRg"];

  // Prerequisite skills
  pre_shinbox -> mov_altshinbox;
  ext_2h_backposside2side -> ext_2h_sc;
  ext_2h_deadclean -> mov_cap;
  ext_2h_sc:s -> mov_kneelsc;
  ext_2h_backposside2side -> mov_kneelbackswing;
  ext_2h_incircle -> ext_2h_outcircle;
  ext_2h_incircle -> mov_incirclesquat;
  ext_2h_outcircle -> mov_outcirclesquat;
  ext_2h_pullover -> ext_2h_backposside2side;
  ext_2h_pullover -> ext_2h_sc;
  ext_2h_pullover -> mov_sblungepull;
  ext_2h_squat -> ext_2h_stepbacklunge;
  ext_2h_squat -> mov_incirclesquat;
  ext_2h_squat -> mov_squatpress;
  ext_2h_frontpress -> mov_cap;
  ext_2h_frontpress -> mov_squatpress;
  ext_2h_frontpress -> mov_sbfrontpress;
  ext_2h_stepbacklunge -> mov_sblungepull;
  ext_2h_sc -> mov_millprep;
  ext_2h_incircle -> mov_millprep;
  ext_2h_squat -> mov_39_pullsquat;
  ext_2h_pullover -> mov_39_pullsquat;
  {ext_2h_swingclean, ext_2h_pullover} -> mov_40_swipe

  mov_fbpull -> mov_fbpullsit;
  mov_sblungepull -> mov_sblungepullbot;
  mov_fbpullsit -> mov_fbpullsitpress;
  mov_altshinbox -> mov_altshinboxfrpress;
  mov_incirclesquat -> mov_outcirclesquat;
  mov_sblungepullbot -> mov_sblungepullsbpress;
  mov_sbfrontpress -> mov_sblungepullsbpress;

  { rank = sink;
    Legend [shape=none, margin=0, label=<
    <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="4">
     <TR>
      <TD COLSPAN="2"><B>Legend</B></TD>
     </TR>
     <TR>
      <TD>Previous Drills</TD>
      <TD BGCOLOR="3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
     </TR>
     <TR>
      <TD>Primary Drills</TD>
      <TD BGCOLOR="11"></TD>
     </TR>
     <TR>
      <TD>Secondary Drills</TD>
      <TD BGCOLOR="7"></TD>
     </TR>
    </TABLE>
   >];
  }
}
@enduml
