@startdot hc_sa_progression
digraph HCSA {

  // YouTube Playlist: https://www.youtube.com/playlist?list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw
  label=<
<B>Single Arm Heavy Club Skill Progression</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
Diagram by dznz based on Mark Wildman's teachings.<BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
Source: <B>https://github.com/dznz/wildman-skill-trees</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
More by Mark Wildman - <B>https://www.wildmanathletica.com</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
<I>
© 2023. This work is openly licensed with CC BY-NC-SA 4.0<BR ALIGN="RIGHT"/>
http://creativecommons.org/licenses/by-nc-sa/4.0/<BR ALIGN="RIGHT"/>
</I>
  >
  graph [labeljust=r]
  graph [fontname="Helvetica,Arial,sans-serif"]

  node [colorscheme="paired12"]
  node [shape=record]
  node [style="rounded,filled"]
  node [color=12, fillcolor=11]

  subgraph warmup {
    node [color=8, fillcolor=7]
  }

  subgraph aux {
    node [color=10, fillcolor=9]
    mov_05_backs2s, mov_06_perry, mov_17_millprep, mov_23_outpull3count
  }

  // Movements external to this diagram
  subgraph ext {
    node [color=4, fillcolor=3]
    ext_2h_s2s, ext_2h_sideswingl2h, ext_2h_sc, ext_2h_pullover
    ext_2h_s2srockit
    ext_2h_incircle, ext_2h_outcircle
    ext_2h_outpend, ext_2h_inpend, ext_2h_altpend
  }

  ext_2h_s2s          [label="{{2H-01|Two-Hand\nSide to Side Swing}}"]
  ext_2h_incircle     [label="{{2H-05|Two-Hand\nInside Circle}}"]
  ext_2h_outcircle    [label="{{2H-06|Two-Hand\nOutside Circle}}"]
  ext_2h_sc           [label="{{2H-09|Two-Hand\nShield Cast}}"]
  ext_2h_sideswingl2h [label="{{2H-02|Two-Hand\nSide Swing\nLow to High}}" ]
  ext_2h_s2srockit    [label="{{2H-15|Two-Hand\nSide to Side\nRockit}}"                         URL=""];
  ext_2h_pullover     [label="{{2H-07|Two-Hand\nPullover}}" URL="https://www.youtube.com/watch?v=jpIn1Sumg78&list=PLk4oYPJ7TXKiueHS7UMPv-DxNMK6UELds&index=7"]
  ext_2h_outpend      [label="{{2H-16|Two-Hand\nOutside Pendulum}}"]
  ext_2h_inpend       [label="{{2H-16|Two-Hand\nInside Pendulum}}"]
  ext_2h_altpend      [label="{{2H-??|Two-Hand\nAlternating Pendulum}}" URL="https://www.youtube.com/watch?v=GULjXPS_ba4"]
  
  mov_01_s2s              [label="{{01|Side to Side Swing}|ELBOWS LOCKED}"              URL="https://www.youtube.com/watch?v=cosgyt2BQG4&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw"];
  mov_02_incircle         [label="{{02|Inside Circle}}"                                 URL="https://www.youtube.com/watch?v=-gtRj1KEUmw"];
  mov_03_outcircle        [label="{{03|Outside Circle}}"                                URL="https://www.youtube.com/watch?v=Mf2QuZvRtQ4&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=2"];
  mov_04_pullover         [label="{{04|Pullover}}"                                      URL="https://www.youtube.com/watch?v=HHT6TrTLJM8"];
  mov_05_backs2s          [label="{{05|Back Position Swing}|THUMB TO SHIRT}"            URL="https://www.youtube.com/watch?v=sxePeWDR1U0"];
  mov_06_perry            [label="{{06|Perry Cast\naka Bailout}|SAFE FAILURE}"          URL="https://www.youtube.com/watch?v=FpUecSrX_AI&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=3"];
  mov_07_sc               [label="{{07|Shield Cast}}"                                   URL="https://www.youtube.com/watch?v=huwc0g3yLWk&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=4"];
  mov_08_sideswingl2h     [label="{{08|Side Swing\nLow to High\nwith Stop}|HIP SNAP}"   URL="https://www.youtube.com/watch?v=huwc0g3yLWk&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=5"];
  mov_09_s2srockit        [label="{{09|Side to Side Rockit}}"                           URL="https://www.youtube.com/watch?v=I26O1ct_hik&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=6"];
  mov_10_sideswingl2hcont [label="{{10|Side Swing\nLow to High\nContinuous}}"           URL="https://www.youtube.com/watch?v=I26O1ct_hik&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=7"];
  mov_11_altcircle        [label="{{11|Alternating Circle}}"                            URL="https://www.youtube.com/watch?v=I26O1ct_hik&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=8"];
  mov_12_outpend          [label="{{12|Outside Pendulum}}"                              URL="https://www.youtube.com/watch?v=I26O1ct_hik&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=9"];
  mov_13_inpend           [label="{{13|Inside Pendulum}}"                               URL="https://www.youtube.com/watch?v=I26O1ct_hik&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=10"];
  mov_14_outpull          [label="{{14|Outside Pullover}|+ EXT ROTATION}"               URL="https://www.youtube.com/watch?v=sJ5XCgdCMx8&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=14"];
  mov_15_inpull           [label="{{15|Inside Pullover}|+ INT ROTATION}"                URL="https://www.youtube.com/watch?v=sJ5XCgdCMx8&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=15"];
  mov_16_altpend          [label="{{16|Alternating Pendulum}}"                          URL="https://www.youtube.com/watch?v=eIkqXJ5d7V4"];
  mov_17_millprep         [label="{{17|Mill Prep}}"                                     URL="https://www.youtube.com/watch?v=I26O1ct_hik&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=17"];
  mov_18_alt180pull       [label="{{18|Alternating 180 Degree\nPullover}}"              URL="https://www.youtube.com/watch?v=I26O1ct_hik&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=18"];
  mov_19_mill             [label="{{19|Mill}}"                                          URL="https://www.youtube.com/watch?v=I26O1ct_hik&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=19"];
  mov_20_revmill          [label="{{20|Reverse Mill}}"                                  URL="https://www.youtube.com/watch?v=I26O1ct_hik&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=20"];
  mov_21_outcirclesc      [label="{{21|Outside Circle\nShield Cast}|ORDER POS IN MILL}" URL="https://www.youtube.com/watch?v=NdJlzFTbQwo&list=PLk4oYPJ7TXKgCH_TpdUCNs2-m5ZCqx-Pw&index=21"]
  mov_22_outpendoutpull   [label="{{22|Outside Pendulum\nOutside Pullover}}"            URL="https://www.youtube.com/watch?v=b0Ztc-54C_Y"]
  mov_23_outpull3count    [label="{{23|Outside Pullover\n3 Count}}"                     URL="https://www.youtube.com/watch?v=_hJaJVaMPtE"];
  mov_24_outpendoutpull3c [label="{{24|Outside Pendulum\nOutside Pullover\n3 Count}}"   URL="https://www.youtube.com/watch?v=FauiblV5PHg"];

  // external skill links
  ext_2h_s2s -> ext_2h_sideswingl2h -> ext_2h_s2srockit;
  ext_2h_outpend -> ext_2h_inpend -> ext_2h_altpend;
  ext_2h_incircle -> ext_2h_outcircle;
  ext_2h_pullover -> ext_2h_sc;

  // external skill dependencies
  ext_2h_s2s -> mov_01_s2s;
  ext_2h_incircle -> mov_02_incircle;
  ext_2h_outcircle -> mov_03_outcircle;
  ext_2h_sc -> mov_07_sc;
  ext_2h_pullover -> mov_04_pullover;
  ext_2h_sideswingl2h -> mov_08_sideswingl2h;
  ext_2h_s2srockit -> mov_09_s2srockit;
  ext_2h_outpend -> mov_12_outpend;
  ext_2h_inpend -> mov_13_inpend;
  ext_2h_altpend -> mov_16_altpend;

  mov_01_s2s -> mov_08_sideswingl2h;
  mov_01_s2s -> mov_02_incircle;
  mov_02_incircle -> mov_03_outcircle;
  mov_08_sideswingl2h -> mov_09_s2srockit;
  mov_09_s2srockit -> mov_12_outpend;
  mov_03_outcircle -> mov_12_outpend;
  mov_08_sideswingl2h -> mov_10_sideswingl2hcont;
  mov_03_outcircle -> mov_11_altcircle;
  mov_12_outpend -> mov_13_inpend -> mov_16_altpend;
  mov_04_pullover -> mov_07_sc;
  mov_04_pullover -> mov_05_backs2s -> mov_07_sc;
  mov_04_pullover -> mov_06_perry -> mov_07_sc;
  mov_05_backs2s -> mov_14_outpull;
  mov_06_perry -> mov_14_outpull;
  mov_04_pullover -> mov_14_outpull;
  mov_14_outpull -> mov_15_inpull;
  mov_02_incircle -> mov_17_millprep;
  mov_07_sc -> mov_17_millprep;
  mov_17_millprep -> mov_18_alt180pull;
  mov_15_inpull -> mov_18_alt180pull;
  mov_18_alt180pull -> mov_19_mill;
  mov_11_altcircle -> mov_19_mill;
  mov_11_altcircle -> mov_20_revmill;
  mov_18_alt180pull -> mov_20_revmill;
  mov_03_outcircle -> mov_21_outcirclesc;
  mov_17_millprep -> mov_21_outcirclesc;
  {mov_12_outpend, mov_14_outpull} -> mov_22_outpendoutpull;
  mov_14_outpull -> mov_23_outpull3count -> mov_19_mill
  {mov_22_outpendoutpull, mov_23_outpull3count} -> mov_24_outpendoutpull3c

  // LEGEND
  { rank = sink;
    Legend [shape=none, margin=0, label=<
    <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="4" BGCOLOR="1">
     <TR>
      <TD COLSPAN="2"><B>Legend</B></TD>
     </TR>
     <TR>
      <TD>Two-Handed Prerequisites</TD>
      <TD BGCOLOR="3"></TD>
     </TR>
     <TR>
      <TD>Regular Drills</TD>
      <TD BGCOLOR="11">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
     </TR>
     <TR>
      <TD>Learning drills</TD>
      <TD BGCOLOR="9"></TD>
     </TR>
    </TABLE>
   >];
  }
}
@enddot
