@startuml
digraph kb_progression {
  // Kettlebell Basic Skill Progression Diagram © 2023
  // by dznz using knowledge from Mark Wildman is licensed
  // under CC BY-NC-SA 4.0 
  // http://creativecommons.org/licenses/by-nc-sa/4.0/
  label="Kettlebell Basic Skill Progression - Part 1"
  node [colorscheme="paired12"]
  node [shape=record]
  node [style="rounded,filled"]
  node [color=12, fillcolor=11]

  subgraph warmup {
    node [color=8, fillcolor=7]
    mov_atw; mov_halo, mov_atwf2b, mov_atwb2f
  }

  subgraph aux {
    node [color=10, fillcolor=9]
    mov_2hu1hd; mov_2hucleandown; mov_news;
  }

  subgraph post {
    node [color=lightslategrey, fillcolor=ghostwhite]

    ext_bw_squat       [label="{{BW|Squat}}"]
    ext_bw_altshinbox  [label="{{BW|Alt Shin Box}}"]
    ext_hc_dblswing    [label="{{HC|Double Swing}}"]
    ext_hc_dblrockit   [label="{{HC|Double Rockit}}"]

    // Implied
    mov_tgd [label="{{|Turkish Get Down}}"]
    mov_tgu [label="{{|Turkish Get Up}}"]
  }
  
  mov_deadlift [label="{{1|Two Hand Deadlift}|HIP HINGE}" URL="https://www.youtube.com/watch?v=x0XkmM34BPI&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=1"];
  mov_swing [label="{{2|Two Hand Swing}|LEG DRIVE &\nHIP SNAP}" URL="https://www.youtube.com/watch?v=m-S9H2XVvYg&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=2"]
  mov_atw [label="{{3|Around the World}|HAND TRANSITION}" URL="https://www.youtube.com/watch?v=XaegZzSbtr0&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=3"]
  mov_halo [label="{{4|Halo}|GLOBE UP\nORDER POSITION}" URL="https://www.youtube.com/watch?v=25xdtjbFPtw&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=4"]
  mov_atwf2b [label="5|Around the World\nFront to Back" URL="https://www.youtube.com/watch?v=TwlQQXAQpaQ&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=5"]
  mov_atwb2f [label="6|Around the World\nBack to Front" URL="https://www.youtube.com/watch?v=GrRO00YOIWM&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=6"]
  mov_althalo [label="7|Alternating Halo" URL="https://www.youtube.com/watch?v=SMpquy5zSL4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=7"]
  mov_2hu1hd [label="{{8|Two Hand Pickup\nOne Hand Putdown}|RACK POSITION}" URL="https://www.youtube.com/watch?v=eMkDP9VmMc0&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=8"]
  mov_saswing [label="{{9|Single Arm Swing}|THUMB POINTS BACK}" URL="https://www.youtube.com/watch?v=ejPpyLKZ1L4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=9"]
  mov_h2h [label="10|Hand to Hand\nTransition" URL="https://www.youtube.com/watch?v=0Uk0Rdm3QFs&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=10"]
  mov_2hucleandown [label="11|Two Hand Pickup\nClean Putdown" URL="https://www.youtube.com/watch?v=cQC2y-ByaAw&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=11"]
  mov_clean [label="12|Swing Clean" URL="https://www.youtube.com/watch?v=_nIsSXWs5iU&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=12"]
  mov_cleanh2h [label="13|Clean with\nHand Transition" URL="https://www.youtube.com/watch?v=6TVqHl2gtuM&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=13"]
  mov_press [label="14|Single Arm\nOverhead Press" URL="https://www.youtube.com/watch?v=XHkI03S6Pls&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=14"]
  mov_news [label="15|Newspaper drill" URL="https://www.youtube.com/watch?v=htByOXjHLXE&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=15"]
  mov_startstopclean [label="{{16|Start Stop Clean}|START & END CLEAN}" URL="https://www.youtube.com/watch?v=XbK3jxI0WNQ&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=16"]
  mov_cap [label="17|Clean & Press" URL="https://www.youtube.com/watch?v=SSxB3m5qRas&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=17"]
  mov_caph2h [label="18|Clean & Press with\nHand Transition" URL="https://www.youtube.com/watch?v=5Q4vMOYvAGg&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=18"]
  mov_startstopcap [label="{{19|Start Stop\nClean & Press}|START & END C&P}" URL="https://www.youtube.com/watch?v=dSj3kqbuois&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=19"]
  mov_gobboxsquat [label="{{20|Bottoms-Up Goblet\nBox Squat}|SQUAT BACK}" URL="https://www.youtube.com/watch?v=k5Bc7pkEmrU&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=20"]
  mov_boxsquathalo [label="{{21|Goblet Box Squat\nwith Halo}|STAND AT TOP}" URL="https://www.youtube.com/watch?v=Aik5-BStbnc&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=21"]
  mov_gobsquathalo [label="{{22|Goblet Squat\nwith Halo}|FULL DEPTH}" URL="https://www.youtube.com/watch?v=cnZ8Mx8NQPE&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=22"]
  mov_racksquat [label="{{23|Single-Bell Front Squat}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=23"]
  mov_racklunge [label="{{24|Rack Opposite Leg\nStep-Back Lunge}|VERTICAL SPINE}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=24"]
  mov_clean2sblunge [label="{{25|Clean Step-Back Clean}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=25"]
  mov_halfkneelclean [label="{{26|Half-Kneeling Clean}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=26"]
  mov_cleansblungeclean [label="{{27|Clean Step-Back\nLunge Clean}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=27"]
  mov_floorpress [label="{{28|Single-Bell Floor Press}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=28"]
  mov_halfkneelcap [label="{{29|Half-Kneeling\nClean & Press}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=29"]
  mov_floorpressroll [label="{{30|Floor Press with Roll}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=30"]
  mov_kneelwindmill [label="{{31|Half-Kneeling Windmill}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=31"]
  mov_quartgu [label="{{32|Quarter Turkish Get-Up}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=32"]
  mov_kneelcapwindmill [label="{{33|Half-Kneeling\nClean & Press Windmill}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=34"]
  mov_halfgu [label="{{34|Half Get-Up}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=35"]
  mov_cap2ohsblunge [label="{{35|Clean & Press to Overhead\nStep-Back Lunge}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=37"]
  mov_kneelhipdrop [label="{{36|Half-Kneeling Hip Drop}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=38"]
  mov_halfgu2hip [label="{{37|Half Get-Up\nto Hip Pass}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=39"]
  mov_kneelcap2hip [label="{{38|Half-Kneeling Clean & Press\nto Hip Drop}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=40"]
  
  mov_boxsquat2boat      [label="{{39|Box Squat to Boat Pose}}"              URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=41"]
  mov_bwspinalrock       [label="{{40|Spinal Rock\n(Bodyweight)}}"           URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=42"]
  mov_flatbackpullover   [label="{{41|Flat Back Pullover}}"                  URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=43"]
  mov_halfgu2kneel [label="{{42|Half Get-Up to Hip Pass\n(to Half-Kneeling)}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=45"]
  
  mov_spinalrock         [label="{{43|Spinal Rock}}"                         URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=48"]
  mov_pushpress          [label="{{44|Push Press}}"                          URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=49"]
  mov_gobsquatcurl       [label="{{45|Rock-Bottom\nCurl with Goblet Squat}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=50"]
  // Missing 46
  mov_racksquatpickup    [label="{{47|Rock-Bottom\nFront Squat Pickup}|PAUSE AT BOTTOM}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=52"]
  mov_thruster           [label="{{48|Thruster}}"                                        URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=48"]
  mov_seatedpress        [label="{{49|Seated Two-Handed\nOverhead Press}}"               URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=54"]
  mov_2hdeadclean2rack   [label="{{50|Two-Handed Dead Clean\nto Double Front Rack}}"     URL="https://www.youtube.com/watch?v=acqKxfMGAbk&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=55"]
  mov_fourcountsquat     [label="{{51|Four-Count Squat\n(Bodyweight)}}"                  URL="https://www.youtube.com/watch?v=1rkGfL1EdWI"]
  mov_rackaltshinbox     [label="{{52|Rack Alt Shinbox}}"                                URL="https://www.youtube.com/watch?v=AoEYX36Q2Zg"]
  mov_hornygobsquat      [label="{{53|Handle Up\nGoblet Squat}}"                         URL="https://www.youtube.com/watch?v=i2AtDi4yZSA"]
  mov_shinboxpress       [label="{{54|Contra Shinbox Press}}"                            URL="https://www.youtube.com/watch?v=FEbi2lKVEHU"]
  mov_backpullsituppress [label="{{55|Flat Back Pullover Situp Press}}"                  URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=57"]
  mov_suitcasedl         [label="{{56|Suitcase Deadlift}}"                               URL="https://www.youtube.com/watch?v=d6i6MwVOmk0&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=58"];
  mov_dblsuitcase        [label="{{57|Double Suitcase}}"                                 URL="https://www.youtube.com/watch?v=4PSOSrDcGfc&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=59"];
  mov_dblsumodl          [label="{{58|Double Sumo Deadlift}}"                            URL="https://www.youtube.com/watch?v=gdutIla6nMw"];
  mov_halfsnatchdown     [label="{{59|Half Snatch Down}}"                                URL="https://www.youtube.com/watch?v=u2NbMtX_Rb0&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=60"];
  mov_dblswing           [label="{{60|Double Swing}}"                                    URL="https://www.youtube.com/watch?v=P5IFTJySA_s&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=61"];
  mov_halfsnatchup       [label="{{61|Half Snatch Up}}"                                  URL="https://www.youtube.com/watch?v=3HEmUyLYjjc"];
  mov_dblclean           [label="{{62|Double Clean}}"                                    URL="https://www.youtube.com/watch?v=Qe9ejhAtdGY&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=62"];
  //63?
  mov_dbloutswing        [label="{{64|Double\nOutside Swing}}"             URL="https://www.youtube.com/watch?v=yr_fRgGevsE"];
  mov_dblrockit          [label="{{64?|Double Rockit}}"                    URL="https://www.youtube.com/watch?v=zXB6hFrrBkA&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=63"];
  mov_dblcap             [label="{{65|Double\nClean & Press}}"             URL="https://www.youtube.com/watch?v=RizGV8ef--s"];
  mov_snatch             [label="{{66|Full Snatch}}"                       URL="https://www.youtube.com/watch?v=f-zkPiAlpQw&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=65"];
  mov_dblsquat           [label="{{67|Double\nFront Squat}}"               URL="https://www.youtube.com/watch?v=dX5yXJa5Dm0&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=66"];
  mov_dblclean2squat     [label="{{68|Double Clean\nto Front Squat}}"      URL="https://www.youtube.com/watch?v=R3s6Wb_ApHM"];
  mov_snatchpress        [label="{{69|Snatch Press}}"                      URL="https://www.youtube.com/watch?v=IzFPa_Q1yHM&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=67"];
  mov_kneelsnatchup      [label="{{70|Half-Kneeling Snatch Up}}"           URL="https://www.youtube.com/watch?v=1_UrK5SopL4"];
  mov_deaddblclean       [label="{{71|Dead Stop\nDouble Clean}}"           URL="https://www.youtube.com/watch?v=22bKQqMqAQY"];
  mov_deck               [label="{{72|Deck Squat}}"                        URL="https://www.youtube.com/watch?v=vUJ3sZVwZ4Y"];
  mov_2hsbldl            [label="{{73|Two Hand Single Bent Leg Deadlift}}" URL="https://www.youtube.com/watch?v=-RD1qqe7P8M"];


  // Next skills
  mov_racklunge [label="{{24|Rack Opposite Leg\nStep-Back Lunge}|VERTICAL SPINE}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=24"]
  mov_clean2sblunge [label="{{25|Clean Step-Back Clean}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=25"]
  mov_halfkneelclean [label="{{26|Half-Kneeling Clean}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=26"]
  mov_halfkneelcap [label="{{29|Half-Kneeling\nClean & Press}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=29"]

  mov_deadlift -> mov_swing;
  mov_deadlift -> mov_atw;
  mov_deadlift -> mov_halo;
  mov_deadlift -> mov_2hu1hd;
  mov_swing -> mov_saswing;
  mov_saswing -> mov_h2h;
  mov_2hu1hd -> mov_2hucleandown;
  mov_saswing -> mov_2hucleandown;
  mov_clean -> mov_cleanh2h;
  mov_2hu1hd -> mov_press;
  mov_halo -> mov_gobboxsquat;
  mov_h2h -> mov_cleanh2h;

  mov_2hu1hd -> mov_racksquat;
  mov_racksquat -> mov_racklunge;
  mov_startstopclean -> mov_clean2sblunge;

  mov_startstopcap -> mov_halfkneelcap;

  subgraph cluster_warmup {
    label="Warmups"
    mov_halo -> mov_althalo;
    mov_atw -> mov_atwf2b;
    mov_atwf2b -> mov_atwb2f;

  }

  subgraph cluster_cap {
    label="Clean & Press"
    mov_2hucleandown -> mov_clean;
    mov_clean -> mov_startstopclean;
    mov_clean -> mov_cap;
    mov_clean -> mov_news;
    mov_press -> mov_cap;
    mov_cap -> mov_caph2h;
    mov_cleanh2h -> mov_caph2h;
    mov_cap -> mov_startstopcap;
  }

 subgraph cluster_tgd {
    label="Turkish Get Down/\nTurkish Get Up"
    mov_racklunge -> mov_clean2sblunge;
    mov_clean2sblunge -> mov_halfkneelclean;
    mov_halfkneelclean -> mov_cleansblungeclean;
    mov_halfkneelclean -> mov_halfkneelcap;
    mov_halfkneelcap -> mov_kneelwindmill;
    mov_kneelwindmill -> mov_kneelcapwindmill;
    mov_kneelcapwindmill -> mov_cap2ohsblunge;
    mov_cleansblungeclean -> mov_cap2ohsblunge;
    mov_kneelcapwindmill -> mov_kneelhipdrop;
    mov_kneelhipdrop -> mov_kneelcap2hip;
    mov_floorpress -> mov_floorpressroll;
    mov_floorpressroll -> mov_quartgu;
    mov_quartgu -> mov_halfgu;
    mov_halfgu -> mov_halfgu2hip;
    mov_halfgu2hip -> mov_halfgu2kneel;
  }

  mov_cap2ohsblunge -> mov_tgd;
  mov_cap2ohsblunge -> mov_tgu;
  mov_kneelcap2hip -> mov_tgd;
  mov_kneelcap2hip -> mov_tgu;
  mov_halfgu2kneel -> mov_tgd;
  mov_halfgu2kneel -> mov_tgu;

  ext_bw_squat -> mov_fourcountsquat
  ext_bw_altshinbox -> mov_rackaltshinbox;
  mov_clean -> mov_2hdeadclean2rack;



  mov_startstopcap -> mov_pushpress;
  mov_gobsquatcurl -> mov_boxsquat2boat;
  mov_hornygobsquat -> mov_boxsquat2boat;
  mov_gobsquathalo -> mov_gobsquatcurl;
  mov_gobsquathalo -> mov_hornygobsquat;
  mov_racksquat -> mov_racksquatpickup;
  mov_racksquat -> mov_thruster;

  // Ungrouped drills
  mov_pushpress -> mov_thruster;
  mov_backpullsituppress -> mov_deck;

  subgraph cluster_squat {
    label="Squats & Getup"

    // Getups
    mov_rackaltshinbox -> mov_shinboxpress
    mov_flatbackpullover -> mov_backpullsituppress;
    mov_seatedpress -> mov_backpullsituppress;

    // Squats
    mov_gobboxsquat -> mov_boxsquathalo;
    mov_boxsquathalo -> mov_gobsquathalo;
    mov_gobsquathalo -> mov_racksquat;
    mov_boxsquat2boat -> mov_deck;
    mov_bwspinalrock -> mov_spinalrock;
    mov_spinalrock -> mov_deck;
    mov_gobsquatcurl
    mov_racksquatpickup
    mov_fourcountsquat
    mov_hornygobsquat
  }

  ext_hc_dblswing -> ext_hc_dblrockit;
  ext_hc_dblrockit -> mov_dblrockit;
  mov_h2h -> mov_dblswing;
  

  mov_startstopclean -> mov_dblclean;
  mov_startstopclean -> mov_halfsnatchdown;
  mov_startstopcap -> mov_dblcap;
  mov_deadlift -> mov_suitcasedl;


  // Ungrouped drills
  mov_suitcasedl -> mov_dblsuitcase;
  mov_suitcasedl -> mov_2hsbldl;

  subgraph cluster_double {
    label="Doubles"
    mov_dbloutswing -> mov_dblrockit
    mov_dblsuitcase -> mov_dblsumodl;
    mov_dblswing -> mov_dblclean;
    mov_dblclean -> mov_dblcap;
    mov_dblclean -> mov_dblsquat;
    mov_dblsquat -> mov_dblclean2squat;
    mov_dblclean -> mov_deaddblclean;
    mov_dblsumodl -> mov_dblswing;
    mov_dblswing -> mov_dbloutswing;
  }

  subgraph cluster_snatch {
    label="Snatch"
    mov_halfsnatchdown -> mov_halfsnatchup -> mov_snatch;
    mov_snatch -> mov_snatchpress;
    mov_snatch -> mov_kneelsnatchup;
  }

  { rank = sink;
    Legend [shape=none, margin=0, label=<
    <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="4">
     <TR>
      <TD COLSPAN="2"><B>Legend</B></TD>
     </TR>
     <TR>
      <TD>Prerequisites and next steps</TD>
      <TD BGCOLOR="ghostwhite">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
     </TR>
     <TR>
      <TD>Drills</TD>
      <TD BGCOLOR="11"></TD>
     </TR>
     <TR>
      <TD>Warmup drills</TD>
      <TD BGCOLOR="7"></TD>
     </TR>
     <TR>
      <TD>Learning drills</TD>
      <TD BGCOLOR="9"></TD>
     </TR>
    </TABLE>
   >];
  }
}
@enduml
