@startdot kb_progression_4
digraph kb_progression {

  label=<
<B>Kettlebell Basic Skill Progression - Part 4/4</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
Diagram by dznz based on Mark Wildman's teachings.<BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
Source: <B>https://github.com/dznz/wildman-skill-trees</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
More by Mark Wildman - <B>https://www.wildmanathletica.com</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
<I>
© 2023. This work is openly licensed with CC BY-NC-SA 4.0<BR ALIGN="RIGHT"/>
http://creativecommons.org/licenses/by-nc-sa/4.0/<BR ALIGN="RIGHT"/>
</I>
  >
  graph [labeljust=r]
  graph [fontname="Helvetica,Arial,sans-serif"]

  node [colorscheme="paired12"]
  node [shape=record]
  node [style="rounded,filled"]
  node [color=12, fillcolor=11]

  subgraph pre {
    node [color=2, fillcolor=1]
    ext_hc_dblswing    [label="{{HC|Double Swing}}"]
    ext_hc_dblrockit   [label="{{HC|Double Rockit}}"]
    
    mov_01_deadlift       [label="{{KB-01|Two Hand Deadlift}|HIP HINGE}"               URL="https://www.youtube.com/watch?v=x0XkmM34BPI&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=1"];
    mov_10_h2h            [label="{{KB-10|Hand to Hand\nTransition}}"                  URL="https://www.youtube.com/watch?v=0Uk0Rdm3QFs&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=10"]
    mov_12_clean          [label="KB-12|Swing Clean"                                   URL="https://www.youtube.com/watch?v=_nIsSXWs5iU&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=12"]
    mov_16_startstopclean [label="{{KB-16|Start Stop Clean}|START & END CLEAN}"        URL="https://www.youtube.com/watch?v=XbK3jxI0WNQ&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=16"]
    mov_17_cap            [label="KB-17|Clean & Press"                                 URL="https://www.youtube.com/watch?v=SSxB3m5qRas&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=17"]
    mov_19_startstopcap   [label="{{KB-19|Start Stop\nClean & Press}|START & END C&P}" URL="https://www.youtube.com/watch?v=dSj3kqbuois&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=19"]

  }

  mov_56_suitcasedl         [label="{{56|Suitcase Deadlift}}"                               URL="https://www.youtube.com/watch?v=d6i6MwVOmk0&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=58"];
  mov_57_dblsuitcase        [label="{{57|Double Suitcase}}"                                 URL="https://www.youtube.com/watch?v=4PSOSrDcGfc&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=59"];
  mov_58_dblsumodl          [label="{{58|Double Sumo Deadlift}}"                            URL="https://www.youtube.com/watch?v=gdutIla6nMw"];
  mov_59_halfsnatchdown     [label="{{59|Half Snatch Down}}"                                URL="https://www.youtube.com/watch?v=u2NbMtX_Rb0&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=60"];
  mov_60_dblswing           [label="{{60|Double Swing}}"                                    URL="https://www.youtube.com/watch?v=P5IFTJySA_s&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=61"];
  mov_61_halfsnatchup       [label="{{61|Half Snatch Up}}"                                  URL="https://www.youtube.com/watch?v=3HEmUyLYjjc"];
  mov_62_dblclean           [label="{{62|Double Clean}}"                                    URL="https://www.youtube.com/watch?v=Qe9ejhAtdGY&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=62"];
  //63 is missing, so we put the Double Rockit in its place
  mov_63_dblrockit          [label="{{63|Double Rockit}}"                     URL="https://www.youtube.com/watch?v=zXB6hFrrBkA&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=63"];
  mov_64_dbloutswing        [label="{{64|Double\nOutside Swing}}"             URL="https://www.youtube.com/watch?v=yr_fRgGevsE"];
  mov_65_dblcap             [label="{{65|Double\nClean & Press}}"             URL="https://www.youtube.com/watch?v=RizGV8ef--s"];
  mov_66_snatch             [label="{{66|Full Snatch}}"                       URL="https://www.youtube.com/watch?v=f-zkPiAlpQw&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=65"];
  mov_67_dblsquat           [label="{{67|Double\nFront Squat}}"               URL="https://www.youtube.com/watch?v=dX5yXJa5Dm0&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=66"];
  mov_68_dblclean2squat     [label="{{68|Double Clean\nto Front Squat}}"      URL="https://www.youtube.com/watch?v=R3s6Wb_ApHM"];
  mov_69_snatchpress        [label="{{69|Snatch Press}}"                      URL="https://www.youtube.com/watch?v=IzFPa_Q1yHM&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=67"];
  mov_70_kneelsnatchup      [label="{{70|Half-Kneeling Snatch Up}}"           URL="https://www.youtube.com/watch?v=1_UrK5SopL4"];
  mov_71_deaddblclean       [label="{{71|Dead Stop\nDouble Clean}}"           URL="https://www.youtube.com/watch?v=22bKQqMqAQY"];
  // 72|Deck Squat is in part 3
  mov_73_2hsbldl            [label="{{73|Two Hand Single\nBent Leg Deadlift}}"                  URL="https://www.youtube.com/watch?v=-RD1qqe7P8M"];
  mov_74_dblhangclean2squat [label="{{74|Double Hang Clean\nTo Squat}}"                         URL="https://www.youtube.com/watch?v=SdPEkv56Lt8"];
  mov_75_2hssldl            [label="{{75|Two Hand Single\nStraight Leg Deadlift}}"              URL="https://www.youtube.com/watch?v=tMt2hzfFGzo"];
  mov_76_dblhangcap         [label="{{76|Double Dead Hang\nClean & Press}|SLOW DOWN TO ENDURE}" URL="https://www.youtube.com/watch?v=ieDA4V9WGNQ"];
  mov_77_shsldl             [label="{{77|Single Hand\nSingle Leg Deadlift}|ONE-SIDE BALANCE}"   URL="https://www.youtube.com/watch?v=1K4hgXfUinU"];
  mov_78_dblcleansqpress    [label="{{78|Double Clean Squat Press}}"                            URL="https://www.youtube.com/watch?v=fWPDPBliCEk"];
  mov_79_kneelsnatchdown    [label="{{79|Half-Kneeling Snatch Down}|KB CLOSE TO BODY}"          URL="https://www.youtube.com/watch?v=okO-7womT5Q"];
  mov_80_dblhangcsp         [label="{{80|Double Dead\nHang Clean\nSquat Press}}"                URL="https://www.youtube.com/watch?v=DpGOSw7kGO0"];
  mov_81_kneelsnatch        [label="{{81|Half Kneeling\nFull Snatch}}"                          URL="https://www.youtube.com/watch?v=axx4kfUzkl4"];
  mov_82_dblcleanpresssq    [label="{{82|Double Clean\nPress Squat}}"                           URL="https://www.youtube.com/watch?v=t5fDkX3vjiU"];
  mov_83_dblcleansblunge    [label="{{83|Double Clean\nRack Step Back Lunge}}"                  URL="https://www.youtube.com/watch?v=mNt7guHRP4U"];

  // Precursor dependencies
  ext_hc_dblswing -> ext_hc_dblrockit;
  ext_hc_dblrockit -> mov_63_dblrockit;
  mov_10_h2h -> mov_60_dblswing;
  
  mov_12_clean -> mov_16_startstopclean;
  mov_12_clean -> mov_17_cap;
  mov_17_cap -> mov_19_startstopcap;
  
  mov_16_startstopclean -> mov_62_dblclean;
  mov_16_startstopclean -> mov_59_halfsnatchdown;
  mov_19_startstopcap -> mov_65_dblcap;
  mov_01_deadlift -> mov_56_suitcasedl;


  // Ungrouped drills
  mov_56_suitcasedl -> mov_57_dblsuitcase;

  subgraph cluster_deadlift {
    label="Deadlifts"
    mov_56_suitcasedl -> mov_73_2hsbldl;
    mov_73_2hsbldl -> mov_75_2hssldl -> mov_77_shsldl;
  }

  subgraph cluster_double {
    label="Doubles"
    mov_64_dbloutswing -> mov_63_dblrockit
    mov_57_dblsuitcase -> mov_58_dblsumodl;
    mov_60_dblswing -> mov_62_dblclean;
    mov_62_dblclean -> mov_65_dblcap;
    mov_62_dblclean -> mov_67_dblsquat;
    mov_67_dblsquat -> mov_68_dblclean2squat;
    mov_62_dblclean -> mov_71_deaddblclean;
    mov_58_dblsumodl -> mov_60_dblswing;
    mov_60_dblswing -> mov_64_dbloutswing;
    mov_68_dblclean2squat -> mov_74_dblhangclean2squat;
    mov_65_dblcap -> mov_76_dblhangcap;
    {mov_76_dblhangcap, mov_68_dblclean2squat} -> mov_78_dblcleansqpress;
    {mov_74_dblhangclean2squat, mov_78_dblcleansqpress} -> mov_80_dblhangcsp;
    {mov_78_dblcleansqpress} -> mov_82_dblcleanpresssq
    {mov_68_dblclean2squat} -> mov_83_dblcleansblunge
  }

  subgraph cluster_snatch {
    label="Snatch"
    mov_59_halfsnatchdown -> mov_61_halfsnatchup -> mov_66_snatch;
    mov_70_kneelsnatchup -> mov_79_kneelsnatchdown -> mov_81_kneelsnatch -> mov_66_snatch
    mov_66_snatch -> mov_69_snatchpress;
  }
  mov_19_startstopcap -> mov_70_kneelsnatchup;

  { rank = sink;
    Legend [shape=none, margin=0, label=<
    <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="4">
     <TR>
      <TD COLSPAN="2"><B>Legend</B></TD>
     </TR>
     <TR>
      <TD>Prerequisites and next steps</TD>
      <TD BGCOLOR="1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
     </TR>
     <TR>
      <TD>Drills</TD>
      <TD BGCOLOR="11"></TD>
     </TR>
    </TABLE>
   >];
  }
}
@enddot
