@startdot kb_progression_2_tgu
digraph kb_progression {

  label=<
<B>Kettlebell Basic Skill Progression - Part 2/4<BR ALIGN="LEFT"/>
- Turkish Get Up</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
Diagram by dznz based on Mark Wildman's teachings.<BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
Source: <B>https://github.com/dznz/wildman-skill-trees</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
More by Mark Wildman - <B>https://www.wildmanathletica.com</B><BR ALIGN="LEFT"/><BR ALIGN="LEFT"/>
<I>
© 2023. This work is openly licensed with CC BY-NC-SA 4.0<BR ALIGN="RIGHT"/>
http://creativecommons.org/licenses/by-nc-sa/4.0/<BR ALIGN="RIGHT"/>
</I>
  >
  graph [labeljust=r]
  graph [fontname="Helvetica,Arial,sans-serif"]

  node [colorscheme="paired12"]
  node [shape=record]
  node [style="rounded,filled"]
  node [color=12, fillcolor=11]

  subgraph pre {
    node [color=lightslategrey, fillcolor=ghostwhite]
    mov_23_racksquat
    mov_17_cap, mov_19_startstopcap
    mov_12_clean, mov_16_startstopclean

    // Implied
    mov_tgd [label="{{|Turkish Get Down}}"]
    mov_tgu [label="{{|Turkish Get Up}}"]
  }
  
  // Precursor drills 
  mov_12_clean          [label="{{KB-12|Swing Clean}}"                               URL="https://www.youtube.com/watch?v=_nIsSXWs5iU&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=12"]
  mov_16_startstopclean [label="{{KB-16|Start Stop Clean}|START & END CLEAN}"        URL="https://www.youtube.com/watch?v=XbK3jxI0WNQ&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=16"]
  mov_17_cap            [label="{{KB-17|Clean & Press}}"                             URL="https://www.youtube.com/watch?v=SSxB3m5qRas&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=17"]
  mov_19_startstopcap   [label="{{KB-19|Start Stop\nClean & Press}|START & END C&P}" URL="https://www.youtube.com/watch?v=dSj3kqbuois&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=19"]
  mov_23_racksquat      [label="{{KB-23|Single-Bell Front Squat}}"                   URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=23"]

  // Sequence
  
  mov_24_racklunge         [label="{{24|Rack Opposite Leg\nStep-Back Lunge}|VERTICAL SPINE}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=24"]
  mov_25_clean2sblunge     [label="{{25|Clean Step-Back Clean}}"                             URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=25"]
  mov_26_halfkneelclean    [label="{{26|Half-Kneeling Clean}}"                               URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=26"]
  mov_27_cleansblungeclean [label="{{27|Clean Step-Back\nLunge Clean}}"                      URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=27"]
  mov_28_floorpress        [label="{{28|Single-Bell Floor Press}}"                           URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=28"]
  mov_29_halfkneelcap      [label="{{29|Half-Kneeling\nClean & Press}}"                      URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=29"]
  mov_30_floorpressroll    [label="{{30|Floor Press with Roll}}"                             URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=30"]
  mov_31_kneelwindmill     [label="{{31|Half-Kneeling Windmill}}"                            URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=31"]
  mov_32_quartgu           [label="{{32|Quarter Turkish Get-Up}}"                            URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=32"]
  mov_33_kneelcapwindmill  [label="{{33|Half-Kneeling\nClean & Press Windmill}}"             URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=34"]
  mov_34_halfgu            [label="{{34|Half Get-Up}}"                                       URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=35"]

  mov_35_cap2ohsblunge  [label="{{35|Clean & Press to Overhead\nStep-Back Lunge}}"  URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=37"]
  mov_36_kneelhipdrop   [label="{{36|Half-Kneeling Hip Drop}}"                      URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=38"]
  mov_37_halfgu2hip     [label="{{37|Half Get-Up\nto Hip Pass}}"                    URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=39"]
  mov_38_kneelcap2hip   [label="{{38|Half-Kneeling Clean & Press\nto Hip Drop}}"    URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=40"]
  // 42 fits better with this diagram
  mov_42_halfgu2kneel   [label="{{42|Half Get-Up to Hip Pass\n(to Half-Kneeling)}}" URL="https://www.youtube.com/watch?v=KTDVl0Lkdc4&list=PLk4oYPJ7TXKhX8YqA2AVrfgs_pEF6p7KA&index=45"]


  // Precursor dependencies
  mov_12_clean -> mov_16_startstopclean;
  mov_12_clean -> mov_17_cap;
  mov_17_cap -> mov_19_startstopcap;
  mov_23_racksquat -> mov_24_racklunge;
  mov_19_startstopcap -> mov_29_halfkneelcap;
  mov_16_startstopclean -> mov_25_clean2sblunge;

  subgraph cluster_tgd {
    label="Turkish Get Down"
    mov_24_racklunge -> mov_25_clean2sblunge;
    mov_25_clean2sblunge -> mov_26_halfkneelclean;
    mov_26_halfkneelclean -> mov_27_cleansblungeclean;
    mov_26_halfkneelclean -> mov_29_halfkneelcap;
    mov_29_halfkneelcap -> mov_31_kneelwindmill;
    mov_31_kneelwindmill -> mov_33_kneelcapwindmill;
    mov_33_kneelcapwindmill -> mov_35_cap2ohsblunge;
    mov_27_cleansblungeclean -> mov_35_cap2ohsblunge;
    mov_33_kneelcapwindmill -> mov_36_kneelhipdrop;
    mov_36_kneelhipdrop -> mov_38_kneelcap2hip;
  }

  mov_35_cap2ohsblunge -> mov_tgd;
  mov_35_cap2ohsblunge -> mov_tgu;
  mov_38_kneelcap2hip -> mov_tgd;
  mov_38_kneelcap2hip -> mov_tgu;
  mov_42_halfgu2kneel -> mov_tgd;
  mov_42_halfgu2kneel -> mov_tgu;

  subgraph cluster_tgu {
    label="Turkish Get Up"
    mov_28_floorpress -> mov_30_floorpressroll;
    mov_30_floorpressroll -> mov_32_quartgu;
    mov_32_quartgu -> mov_34_halfgu;
    mov_34_halfgu -> mov_37_halfgu2hip;
    mov_37_halfgu2hip -> mov_42_halfgu2kneel;
  }
  { rank = sink;
    Legend [shape=none, margin=0, label=<
    <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="4">
     <TR>
      <TD COLSPAN="2"><B>Legend</B></TD>
     </TR>
     <TR>
      <TD>Prerequisites and next steps</TD>
      <TD BGCOLOR="ghostwhite">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
     </TR>
     <TR>
      <TD>Drills</TD>
      <TD BGCOLOR="11"></TD>
     </TR>
    </TABLE>
   >];
  }
}
@enddot
